"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.baseLayout = baseLayout;
/**
 * Base email layout — wraps all invoice email templates.
 * Uses inline styles for maximum email client compatibility.
 */
function baseLayout(_a) {
    var previewText = _a.previewText, content = _a.content, companyName = _a.companyName;
    return "\n<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n  <meta charset=\"UTF-8\" />\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n  <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\n  <title>".concat(companyName, "</title>\n  <!--[if mso]>\n  <noscript>\n    <xml><o:OfficeDocumentSettings><o:PixelsPerInch>96</o:PixelsPerInch></o:OfficeDocumentSettings></xml>\n  </noscript>\n  <![endif]-->\n</head>\n<body style=\"margin:0;padding:0;background-color:#f4f5f7;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;\">\n\n  <!-- Preview text (hidden) -->\n  <span style=\"display:none;max-height:0;overflow:hidden;mso-hide:all;\">\n    ").concat(previewText, "&nbsp;&#847;&nbsp;\n  </span>\n\n  <!-- Outer wrapper -->\n  <table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color:#f4f5f7;padding:40px 16px;\">\n    <tr>\n      <td align=\"center\">\n\n        <!-- Card -->\n        <table role=\"presentation\" width=\"100%\" style=\"max-width:560px;background-color:#ffffff;border-radius:8px;overflow:hidden;box-shadow:0 1px 4px rgba(0,0,0,0.08);\">\n\n          <!-- Header bar -->\n          <tr>\n            <td style=\"background-color:#18181b;padding:24px 32px;\">\n              <p style=\"margin:0;font-size:18px;font-weight:700;color:#ffffff;letter-spacing:-0.3px;\">\n                ").concat(companyName, "\n              </p>\n            </td>\n          </tr>\n\n          <!-- Body -->\n          <tr>\n            <td style=\"padding:32px;\">\n              ").concat(content, "\n            </td>\n          </tr>\n\n          <!-- Footer -->\n          <tr>\n            <td style=\"padding:20px 32px;border-top:1px solid #f0f0f0;background-color:#fafafa;\">\n              <p style=\"margin:0;font-size:12px;color:#9ca3af;line-height:1.6;\">\n                This email was sent by ").concat(companyName, "..\n              </p>\n            </td>\n          </tr>\n\n        </table>\n        <!-- /Card -->\n\n      </td>\n    </tr>\n  </table>\n\n</body>\n</html>\n  ").trim();
}
